name: Build Release APK

on:
  push:
    branches:
      - master  # Replace with your main branch name
  pull_request:
    branches:
      - master  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11  # Replace with your desired Java version
        distribution: 'adopt'  # Replace with your desired Java distribution

    - name: Download and extract Android SDK Command-line Tools
      run: |
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -o android-sdk.zip
        unzip -qq android-sdk.zip -d $HOME/android-sdk

    - name: Set up environment variables
      run: |
        echo 'export ANDROID_SDK_ROOT=$HOME/android-sdk' >> $GITHUB_ENV
        echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools' >> $GITHUB_ENV

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
